pre-commit file size and golang lint

diff --git a/config/pre-commit b/config/pre-commit
--- a/config/pre-commit
+++ b/config/pre-commit
@@ -6,6 +6,56 @@
 # it wants to stop the commit.
 #
 # To enable this hook, rename this file to "pre-commit".
+
+
+# ---------------------------------------------------------------------
+# Проверяем размер файла ----------------------------------------------
+# ---------------------------------------------------------------------
+# This is a pre-commit hook that ensures attempts to commit files that are
+# are larger than $limit to your _local_ repo fail, with a helpful error message.
+
+# Maximum file size limit in bytes
+limit=100000 # 100KB
+limitInMB=$(( $limit / 1000 ))
+
+# Move to the repo root so git files paths make sense
+repo_root=$( git rev-parse --show-toplevel )
+cd $repo_root
+
+empty_tree=$( git hash-object -t tree /dev/null )
+
+if git rev-parse --verify HEAD > /dev/null 2>&1
+then
+	against=HEAD
+else
+	against="$empty_tree"
+fi
+
+# Set split so that for loop below can handle spaces in file names by splitting on line breaks
+IFS='
+'
+
+echo "Checking staged file sizes"
+shouldFail=false
+for file in $( git diff-index --cached --name-only $against ); do
+	file_size=$( ls -la $file | awk '{ print $5 }')
+	if [ "$file_size" -gt  "$limit" ]; then
+	    echo "[\e[31mDANGER\e[0m] File \e[32m$file\e[0m is \e[31m$(( $file_size / 1000 ))\e[0mKB, which is larger than our configured limit of \e[32m$limitInMB\e[0mKB"
+        shouldFail=true
+	fi
+done
+
+if $shouldFail
+then
+    echo If you really need to commit this file, you can push with the --no-verify switch, but the file should definitely, definitely be under 100KB!!!
+	  echo Commit aborted
+    exit 1;
+fi
+
+# ---------------------------------------------------------------------
+# Запускаем линтер только на новых коммитах ---------------------------
+# ---------------------------------------------------------------------
+
 golangci-lint run --fix -new
 if [ $? -eq 0 ]; then echo -e "[\e[32mOK\e[0m] OK lint "; \
 else echo -e "[\e[31mERROR\e[0m] failt lint " >&2; exit 1; fi
