change pre-commit recursive dir

diff --git a/config/pre-commit b/config/pre-commit
--- a/config/pre-commit
+++ b/config/pre-commit
@@ -15,8 +15,8 @@
 # are larger than $limit to your _local_ repo fail, with a helpful error message.
 
 # Maximum file size limit in bytes
-limit=100000 # 100KB
-limitInMB=$(( $limit / 1000 ))
+limit=100 # 100KB
+limitInMB=$(( $limit ))
 
 # Move to the repo root so git files paths make sense
 repo_root=$( git rev-parse --show-toplevel )
@@ -26,9 +26,9 @@ empty_tree=$( git hash-object -t tree /dev/null )
 
 if git rev-parse --verify HEAD > /dev/null 2>&1
 then
-	against=HEAD
+    against=HEAD
 else
-	against="$empty_tree"
+    against="$empty_tree"
 fi
 
 # Set split so that for loop below can handle spaces in file names by splitting on line breaks
@@ -37,18 +37,35 @@ IFS='
 
 echo "Checking staged file sizes"
 shouldFail=false
-for file in $( git diff-index --cached --name-only $against ); do
-	file_size=$( ls -la $file | awk '{ print $5 }')
-	if [ "$file_size" -gt  "$limit" ]; then
-	    echo "[\e[31mDANGER\e[0m] File \e[32m$file\e[0m is \e[31m$(( $file_size / 1000 ))\e[0mKB, which is larger than our configured limit of \e[32m$limitInMB\e[0mKB"
-        shouldFail=true
-	fi
-done
+
+INPUT_FILE=$( git diff-index --cached --name-only $against );
+
+
+check_size ()
+{
+    arg_0="$@"
+    for file in $arg_0; do
+        DU=$( du -a $file )
+        file_size=$(echo $DU | awk '{ print $1 }')
+        file_name=$(echo $DU | awk '{ print $2 }')
+        if [ -d $file_name ]; then
+            check_size $file_name
+        else
+            if [ "$file_size" -gt  "$limit" ]; then
+                echo "[\e[31mDANGER\e[0m] File \e[32m$file\e[0m is \e[31m$(( $file_size ))\e[0mKB, \
+                    which is larger than our configured limit of \e[32m$limitInMB\e[0mKB"
+                                    shouldFail=true
+            fi
+        fi
+    done
+}
+
+check_size $INPUT_FILE
 
 if $shouldFail
 then
     echo If you really need to commit this file, you can push with the --no-verify switch, but the file should definitely, definitely be under 100KB!!!
-	  echo Commit aborted
+    echo Commit aborted
     exit 1;
 fi
 
@@ -57,15 +74,15 @@ fi
 # ---------------------------------------------------------------------
 
 golangci-lint run --fix -new
-if [ $? -eq 0 ]; then echo -e "[\e[32mOK\e[0m] OK lint "; \
-else echo -e "[\e[31mERROR\e[0m] failt lint " >&2; exit 1; fi
+if [ $? -eq 0 ]; then echo "[\e[32mOK\e[0m] OK lint "; \
+else echo "[\e[31mERROR\e[0m] failt lint " >&2; exit 1; fi
 
 if git rev-parse --verify HEAD >/dev/null 2>&1
 then
-	against=HEAD
+    against=HEAD
 else
-	# Initial commit: diff against an empty tree object
-	against=4b825dc642cb6eb9a060e54bf8d69288fbee4904
+    # Initial commit: diff against an empty tree object
+    against=4b825dc642cb6eb9a060e54bf8d69288fbee4904
 fi
 
 # If you want to allow non-ASCII filenames set this variable to true.
@@ -78,13 +95,13 @@ exec 1>&2
 # them from being added to the repository. We exploit the fact that the
 # printable range starts at the space character and ends with tilde.
 if [ "$allownonascii" != "true" ] &&
-	# Note that the use of brackets around a tr range is ok here, (it's
-	# even required, for portability to Solaris 10's /usr/bin/tr), since
-	# the square bracket bytes happen to fall in the designated range.
-	test $(git diff --cached --name-only --diff-filter=A -z $against |
-	  LC_ALL=C tr -d '[ -~]\0' | wc -c) != 0
-then
-	cat <<\EOF
+    # Note that the use of brackets around a tr range is ok here, (it's
+    # even required, for portability to Solaris 10's /usr/bin/tr), since
+    # the square bracket bytes happen to fall in the designated range.
+    test $(git diff --cached --name-only --diff-filter=A -z $against |
+        LC_ALL=C tr -d '[ -~]\0' | wc -c) != 0
+        then
+            cat <<\EOF
 Error: Attempt to add a non-ASCII file name.
 
 This can cause problems if you want to work with people on other platforms.
@@ -95,8 +112,10 @@ If you know what you are doing you can disable this check using:
 
   git config hooks.allownonascii true
 EOF
-	exit 1
+exit 1
 fi
 
 # If there are whitespace errors, print the offending file names and fail.
 exec git diff-index --check --cached $against --
+
+
